version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: back/Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - back/.environment

  frontend:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - "3000:3000"
