###
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "123456"
}

### Budget tests
POST http://localhost:8000/api/trips/41/budget
Content-Type: application/json

{
  "budget": 5000
}
###
GET http://localhost:8000/api/trips/40/budget
###
PUT http://localhost:8000/api/trips/38/budget
Content-Type: application/json

{
  "budget": 3000
}

### Expens Group tests
POST http://localhost:8000/api/trips/37/budget/groups
Content-Type: application/json

{
  "visit": 1,
  "name": "Transport",
  "description": "Transport expenses"
}
###
GET http://localhost:8000/api/trips/37/budget/groups
###
GET http://localhost:8000/api/trips/37/budget/groups/1
###
DELETE http://localhost:8000/api/trips/37/budget/groups/1

### Expense tests
POST http://localhost:8000/api/trips/40/budget/expenses
# expense_group is optional
Content-Type: application/json

{
  "category": "Activity",
  "name": "jump",
  "description": "jumping is good",
  "planned_amount": 10,
  "actual_amount": 9,
  "is_shared": false
}
###
POST http://localhost:8000/api/trips/41/budget/expenses
# expense_group is optional
Content-Type: application/json

{
  "category": "Food",
  "name": "kebab",
  "description": "kebab is good",
  "planned_amount": 10,
  "actual_amount": 9,
  "is_shared": false
}
###
POST http://localhost:8000/api/trips/41/budget/expenses
# expense_group is optional
Content-Type: application/json

{
  "category": "Accommodation",
  "name": "hotel",
  "description": "hotel is good",
  "actual_amount": 500,
  "is_shared": false
}
###
POST http://localhost:8000/api/trips/41/budget/expenses
# expense_group is optional
Content-Type: application/json

{
  "category": "Transport",
  "name": "bus",
  "description": "bus is good",
  "actual_amount": 80,
  "is_shared": false
}
###
POST http://localhost:8000/api/trips/41/budget/expenses
# expense_group is optional
Content-Type: application/json

{
  "category": "Others",
  "name": "others",
  "description": "others is good",
  "actual_amount": 80,
  "is_shared": false
}
###
GET http://localhost:8000/api/trips/41/budget/expenses
###
GET http://localhost:8000/api/trips/37/budget/expenses/10
###
PUT http://localhost:8000/api/trips/37/budget/expenses/10
Content-Type: application/json

{
  "category": 1,
  "name": "New expense",
  "description": "NEW",
  "planned_amount": 1000,
  "actual_amount": 900,
  "is_shared": false,
  "expense_group": 2
}
###
DELETE http://localhost:8000/api/trips/41/budget/expenses/13
### Expense Share tests
POST http://localhost:8000/api/trips/37/budget/expenses/share
Content-Type: application/json

{
  "expense": 10,
  "with_user" : "2026d3b8-da17-4ef4-8067-7c532fe2e4e8",
  "due_amount": 100

}
###
GET http://localhost:8000/api/trips/37/budget/expenses/share/debts
###
GET http://localhost:8000/api/trips/37/budget/expenses/share/refunds
###
GET http://localhost:8000/api/trips/37/budget/expenses/share/4
###
PUT http://localhost:8000/api/trips/37/budget/expenses/share/5
Content-Type: application/json

{
  "expense": 10,
  "with_user" : "2026d3b8-da17-4ef4-8067-7c532fe2e4e8",
  "due_amount": 200
}

###
DELETE http://localhost:8000/api/trips/37/budget/expenses/share/5
###

###
GET http://localhost:8000/api/categories

