###
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "123456"
}


###
GET http://localhost:8000/api/me
###
PUT http://localhost:8000/api/me
Content-Type: application/json

{
  "user_id": "6d7e4d80-5535-4ab9-86f0-f79bb01ea694",
  "alias": "JojoDodo",
  "birthdate": "2001-01-22",
  "description": "I'm a developer",
  "languages": "fr, en, ar"
}

###
GET http://localhost:8000/api/users
###
GET http://localhost:8000/api/users/6d7e4d80-5535-4ab9-86f0-f79bb01ea694