# These API are used to insert data into database by the admin
### Catergory tests
POST http://localhost:8000/api/categories
Content-Type: application/json

{
  "name": "Transport"

}
###
GET http://localhost:8000/api/categories

### Location tests
POST http://localhost:8000/api/locations
Content-Type: application/json

{
  "name": "Hotel",
  "latitude": 0.0,
  "longitude": 0.0,
  "description": "Hotel description"
}
###
GET http://localhost:8000/api/locations
###