### Login
POST http://localhost:8000/api/auth/login
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "123456"
}

### GET all locations
GET http://localhost:8000/api/locations

### GET all locations paginated
GET http://localhost:8000/api/locations?page=5

### GET filtered locations
GET http://localhost:8000/api/locations?lat=48.3&lon=7.5&radius=5&page=1&search=jardin

### GET sorted filtered locations
GET http://localhost:8000/api/locations?lat=48.3&lon=7.5&radius=5&sort_by=name&sort_order=desc&page=1

### GET viewport locations
GET localhost:8000//api/locations?min_price=0&max_price=1000&search=jar&page=1&pageSize=100&only_prices=false&min_lat=48.19607397283394&max_lat=48.33046303150273&min_lon=7.4154278097097945&max_lon=7.6090618429129195

### Visits tests
POST http://localhost:8000/api/trips/1/visits
Content-Type: application/json

{
  "location_id": 2,
  "trip_id": 1,
  "name": "Paris",
  "start_date": "2021-12-01",
  "end_date": "2021-12-10"
}

### GET all visits
GET http://localhost:8000/api/trips/4/visits

### GET visit by id
GET http://localhost:8000/api/trips/4/visits/1

### PUT visit
PUT http://localhost:8000/api/trips/4/visits/2
Content-Type: application/json

{
  "location_id": 2,
  "trip_id": 4,
  "name": "Algiers",
  "start_date": "2021-12-01",
  "end_date": "2021-12-10"
}

### DELETE visit
DELETE http://localhost:8000/api/trips/4/visits/2
